### ISSUE TITLE
Binding required attribute dynamically doesn't work conditionally

### ISSUE THREAD

**Issue by markandrewkato** [ankurk91/vue-jquery-mask#2]
Hi, 

I tried binding the required attribute dynamically like so:

```vue
<vue-mask id="rental_amount"
                    name="amount"
                    mask="000,000,000.00"
                    :options="{reverse: true}"
                    type="text"
                    :required="isRequired"
                    :aria-required="isRequired"></vue-mask>
```

I want the required attribute to be conditional. The plugin generated a `required="required"` attribute even if the `isRequired` data is false.

Is there a way to make this conditional?

**Comment by ankurk91** [comment]
I could not reproduce the issue, see
https://jsfiddle.net/d92xgzhL/75/

![screen-record](https://user-images.githubusercontent.com/6111524/46679741-3b80ce00-cc05-11e8-987d-c71e612d663e.gif)

**Comment by markandrewkato** [comment]
I think this also relates to this issue, https://github.com/ankurk91/vue-jquery-mask/issues/3, wherein if the `vue-mask` element is inside a v-if, the require attribute doesn't work properly
