### ISSUE TITLE
Using v-if doesn't apply proper mask

### ISSUE THREAD

**Issue by markandrewkato** [ankurk91/vue-jquery-mask#3]
I have two masked input fields and I need to show only one of the two. Unfortunately, when I use `v-if` it doesn't apply the proper mask on the second element. It applies the mask of the first element to the second element.

I know`v-show` is an option but in this case, I need to use `v-if` so one of the input won't send data to the server.

**Comment by ankurk91** [comment]
I could not reproduce this issue
https://jsfiddle.net/d92xgzhL/76/

**Comment by markandrewkato** [comment]
Hi. Try this. https://jsfiddle.net/bjrnh5dv/

**Comment by ankurk91** [comment]
i have updated the fiddle.
https://jsfiddle.net/bjrnh5dv/5/

~~It is working fine for me.~~

**Comment by markandrewkato** [comment]
its not working. tried your updated link.

https://screencast.com/t/ywr3G6DrBnrS

**Comment by ankurk91** [comment]
Sorry my browser don't have flash player. I couldn't not play the screencast.
If possible download the video and attach here on GitHub

**Comment by ankurk91** [comment]
Was just able to re-produce it, I will look into it tomorrow.
Thanks for keeping patience

**Comment by ankurk91** [comment]
I was able to solve this issue by adding `key` to component.
https://jsfiddle.net/bjrnh5dv/12/

Notice `key="phone"` attribute.

Read more

https://vuejs.org/v2/guide/list.html#key

**Comment by markandrewkato** [comment]
@ankurk91 all good. thank you.
